### PR TITLE
README Rework

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
Please check the preview **[Preview]**.
Comparison **[Old]** & **[New]** source.

#### Changes

- General formatting / spacing
- Moved usage / caveats into dedicated files
- Moved changelog into `/Documentation/`
- Converted raw links to referenced ones
- Added quicklinks

#### Repository Recommendations

- Disable unused widget `Packages`
- Disable unused tab `Projects`

[Preview]: https://github.com/ElectronicsArchiver/rotating-fos
[Old]: https://github.com/vy/rotating-fos/blob/master/README.md?plain=1
[New]: https://github.com/ElectronicsArchiver/rotating-fos/blob/master/README.md?plain=1

### CODE REVIEW

**Comment by vy** [comment]
Thanks for the contribution @ElectronicsArchiver, though I cannot accept this. A short README file welcoming users with all the sufficient information is split into multiple files with some ASCII decorations, which alone convolutes README for those trying to read from console.

**Comment by ElectronicsArchiver** [comment]
> which alone con-volutes README for those trying to read from console.

And the original doesn't? Is it **just** about separating the content, 
as the original also has formatting?

Why not use a terminal specific `README.txt` file?

**Comment by vy** [comment]
> > which alone con-volutes README for those trying to read from console.
> 
> And the original doesn't? Is it **just** about separating the content, as the original also has formatting?

The original file contains 152 sloc Markdown, way less lines when displayed. At the first glance, user is able to understand what it is, how it works, etc. User doesn't need to navigate to another page. If the project would have contained more features, I would certainly prefer your approach.

> Why not use a terminal specific `README.txt` file?

Because one `README.md` simply serves both purposes well enough?

I am really sorry to reject your contribution. F/OSS contributors are extremely rare to encounter and I don't want to discourage you by any means. Please keep your contributions coming. In order to avoid a similar conflict next time and save you some effort, please discuss your proposal first in a ticket rather than directly submitting a PR.

**Comment by ElectronicsArchiver** [comment]
Thanks & don't worry, as a I mainly contribute to documentation of repositories,
I'm well antiquated with being rejected / having to wait for weeks,.. months,..

**Pull request closed without merging**
